using Kotakas.Web.Data;
using Microsoft.EntityFrameworkCore;

namespace Kotakas.Web.Api;

public static class TraderPackageSchemaSeeder
{
    public static async Task InitializeAsync(WebApplication app)
    {
        using var scope = app.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        if (db.Database.IsNpgsql())
        {
            await db.Database.ExecuteSqlRawAsync("""
                CREATE TABLE IF NOT EXISTS "TraderPackageOrders" (
                    "Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    "UserId" text NOT NULL,
                    "PackageCode" text NOT NULL,
                    "PriceGb" numeric(18,4) NOT NULL,
                    "ListingLimit" integer NOT NULL,
                    "ListingsUsed" integer NOT NULL DEFAULT 0,
                    "DurationDays" integer NOT NULL DEFAULT 30,
                    "Status" text NOT NULL DEFAULT 'pending',
                    "CreatedAt" timestamptz NOT NULL,
                    "ActivatedAt" timestamptz NULL,
                    "ExpiresAt" timestamptz NULL,
                    "ApprovedAt" timestamptz NULL,
                    "ApprovedByUserId" text NULL
                );
                CREATE INDEX IF NOT EXISTS "IX_TraderPackageOrders_User_Status"
                    ON "TraderPackageOrders" ("UserId", "Status", "ExpiresAt");
                CREATE INDEX IF NOT EXISTS "IX_TraderPackageOrders_Status_Created"
                    ON "TraderPackageOrders" ("Status", "CreatedAt");
                """);
            return;
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "TraderPackageOrders" (
                "Id" INTEGER NOT NULL CONSTRAINT "PK_TraderPackageOrders" PRIMARY KEY AUTOINCREMENT,
                "UserId" TEXT NOT NULL,
                "PackageCode" TEXT NOT NULL,
                "PriceGb" NUMERIC NOT NULL,
                "ListingLimit" INTEGER NOT NULL,
                "ListingsUsed" INTEGER NOT NULL DEFAULT 0,
                "DurationDays" INTEGER NOT NULL DEFAULT 30,
                "Status" TEXT NOT NULL DEFAULT 'pending',
                "CreatedAt" TEXT NOT NULL,
                "ActivatedAt" TEXT NULL,
                "ExpiresAt" TEXT NULL,
                "ApprovedAt" TEXT NULL,
                "ApprovedByUserId" TEXT NULL
            );
            CREATE INDEX IF NOT EXISTS "IX_TraderPackageOrders_User_Status"
                ON "TraderPackageOrders" ("UserId", "Status", "ExpiresAt");
            CREATE INDEX IF NOT EXISTS "IX_TraderPackageOrders_Status_Created"
                ON "TraderPackageOrders" ("Status", "CreatedAt");
            """);
    }
}
