import express from 'express';
import bcrypt from 'bcryptjs';
import crypto from 'node:crypto';
import { normalizeEmail, validateRegistrationInput } from './users.js';
import { clearSessionCookie, createSessionToken, setSessionCookie } from './session.js';
import { createIpRateLimit } from '../security/rate-limit.js';
function authResponse(user){return{ok:true,authenticated:Boolean(user),user:user||null}}
function duplicateEmail(e){return e?.code==='23505'||/unique|duplicate/i.test(String(e?.message||''))}
function safeEqual(a,b){const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&crypto.timingSafeEqual(x,y)}
export function createAuthRouter({users,jwtSecret,production}){const router=express.Router(),loginLimit=createIpRateLimit({windowMs:60000,max:12}),registerLimit=createIpRateLimit({windowMs:600000,max:6});
async function register(req,res,next){try{const v=validateRegistrationInput(req.body||{});if(!v.ok)return res.status(400).json({ok:false,error:v.error});const{email,password,displayName}=v.value;if(await users.findAuthUserByEmail(email))return res.status(409).json({ok:false,error:'email_already_registered'});const passwordHash=await bcrypt.hash(password,12);const user=await users.createUser({email,passwordHash,displayName,role:'user'});setSessionCookie(res,createSessionToken({userId:user.id,jwtSecret}),production);return res.status(201).json(authResponse(user))}catch(e){if(duplicateEmail(e))return res.status(409).json({ok:false,error:'email_already_registered'});next(e)}}
async function login(req,res,next){try{const email=normalizeEmail(req.body?.email),password=String(req.body?.password||'');if(!email||!password)return res.status(400).json({ok:false,error:'email_and_password_required'});const au=await users.findAuthUserByEmail(email);if(!au?.user?.active)return res.status(401).json({ok:false,error:'invalid_credentials'});const stored=String(au.passwordHash||'');let correct=false;if(/^\$2[aby]\$/.test(stored))correct=await bcrypt.compare(password,stored);else if(stored&&safeEqual(stored,password)){correct=true;await users.upgradePasswordHash(au.user.id,await bcrypt.hash(password,12));}if(!correct)return res.status(401).json({ok:false,error:'invalid_credentials'});setSessionCookie(res,createSessionToken({userId:au.user.id,jwtSecret}),production);await users.touchLastLogin(au.user.id);return res.json(authResponse(au.user))}catch(e){next(e)}}
function logout(_req,res){clearSessionCookie(res,production);return res.json({ok:true})}function me(req,res){return res.json(authResponse(req.user))}
router.post('/register',registerLimit,register);router.post('/auth/register',registerLimit,register);router.post('/login',loginLimit,login);router.post('/auth/login',loginLimit,login);router.post('/logout',logout);router.post('/auth/logout',logout);router.get('/me',me);router.get('/auth/me',me);return router}
