const TABLE_CANDIDATES = ['users', 'app_users', 'members'];
const COLUMN_ALIASES = Object.freeze({id:['id','user_id'],email:['email','mail'],passwordHash:['password_hash','pass_hash','password'],displayName:['display_name','full_name','name','username'],role:['role','user_role'],active:['is_active','active'],status:['status','account_status'],createdAt:['created_at','created'],updatedAt:['updated_at','updated'],lastLoginAt:['last_login_at','last_login']});
function quoteIdent(v){if(!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(v))throw new Error('invalid_sql_identifier');return `"${v}"`}
function pick(c,a){return a.find(n=>c.has(n))||null}
function normalizeRole(row,s){if(row.is_owner===true)return'admin_owner';if(row.is_admin===true)return'admin_full';if(row.is_trader===true||row.trader_verified===true)return'trader';if(s.role&&row[s.role])return String(row[s.role]);return'user'}
function normalizeActive(row,s){if(s.active)return row[s.active]!==false;if(s.status){const st=String(row[s.status]||'').toLowerCase();if(['blocked','banned','disabled','inactive','deleted'].includes(st))return false}return true}
function publicUser(row,s){if(!row)return null;return{id:s.id?row[s.id]:null,email:s.email?row[s.email]:null,displayName:s.displayName?row[s.displayName]:null,role:normalizeRole(row,s),active:normalizeActive(row,s),createdAt:s.createdAt?row[s.createdAt]:null}}
export function normalizeEmail(v=''){return String(v).trim().toLowerCase()}
export function validateRegistrationInput({email,password,displayName}){const e=normalizeEmail(email),n=String(displayName||'').trim(),p=String(password||'');if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))return{ok:false,error:'invalid_email'};if(p.length<8||p.length>128)return{ok:false,error:'invalid_password_length'};if(n.length<2||n.length>80)return{ok:false,error:'invalid_display_name'};return{ok:true,value:{email:e,password:p,displayName:n}}}
export async function discoverUserSchema(pool){const tr=await pool.query(`select table_name from information_schema.tables where table_schema='public' and table_type='BASE TABLE'`);const at=new Set(tr.rows.map(r=>r.table_name));const table=TABLE_CANDIDATES.find(n=>at.has(n));if(!table)throw new Error('users_table_not_found');const cr=await pool.query(`select column_name from information_schema.columns where table_schema='public' and table_name=$1`,[table]);const columns=new Set(cr.rows.map(r=>r.column_name));const s={table,columns};for(const[k,a]of Object.entries(COLUMN_ALIASES))s[k]=pick(columns,a);if(!s.id||!s.email||!s.passwordHash)throw new Error(`users_schema_incompatible:${table}`);return s}
export function createUserRepository(pool){let schemaPromise;const getSchema=()=>schemaPromise||=(discoverUserSchema(pool));return{
async describeSchema(){const s=await getSchema();return{table:s.table,id:s.id,email:s.email,passwordHash:s.passwordHash,displayName:s.displayName,role:s.role,active:s.active,status:s.status,lastLoginAt:s.lastLoginAt}},
async findAuthUserByEmail(email){const s=await getSchema();const r=await pool.query(`select * from ${quoteIdent(s.table)} where lower(${quoteIdent(s.email)})=lower($1) limit 1`,[normalizeEmail(email)]);const row=r.rows[0];return row?{user:publicUser(row,s),passwordHash:row[s.passwordHash]}:null},
async findPublicUserById(id){const s=await getSchema();const r=await pool.query(`select * from ${quoteIdent(s.table)} where ${quoteIdent(s.id)}=$1 limit 1`,[id]);return publicUser(r.rows[0],s)},
async createUser({email,passwordHash,displayName,role='user'}){const s=await getSchema();const cols=[s.email,s.passwordHash],vals=[normalizeEmail(email),passwordHash];if(s.displayName){cols.push(s.displayName);vals.push(displayName)}if(s.role){cols.push(s.role);vals.push(role)}if(s.active){cols.push(s.active);vals.push(true)}const ph=vals.map((_,i)=>`$${i+1}`).join(', ');const r=await pool.query(`insert into ${quoteIdent(s.table)} (${cols.map(quoteIdent).join(', ')}) values (${ph}) returning *`,vals);return publicUser(r.rows[0],s)},
async upgradePasswordHash(id,passwordHash){const s=await getSchema();await pool.query(`update ${quoteIdent(s.table)} set ${quoteIdent(s.passwordHash)}=$2 where ${quoteIdent(s.id)}=$1`,[id,passwordHash])},
async touchLastLogin(id){const s=await getSchema();if(!s.lastLoginAt)return;await pool.query(`update ${quoteIdent(s.table)} set ${quoteIdent(s.lastLoginAt)}=now() where ${quoteIdent(s.id)}=$1`,[id])}
}}
